---
apiVersion: v1
kind: Pod
metadata:
  name: p1-label
  labels:
    environment: production
    app: nginx
    project: server_developmentt
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80